### ISSUE TITLE
SocialImage sometimes not taken by Twitter

### ISSUE THREAD

**Issue by BsNoSi** [schulle4u/yellow-plugin-socialtags#3] opened 2018-09-21 10:08 UTC
I am very happy with "yellow-plugin-socialtags", it works perfect for me.

In the last few days, however, I have observed an effect for which I lack an explanation: the "SocialtagsImage" seems to be ignored by Twitter.

In the first case, I had entered an incorrect file url, which I corrected and re-sent the tweet a few times (after deleting the previous): still no display of the image. I thought it might be a caching problem, so I didn't follow it any further. Today I definitely used a correct image url, but the image was also ignored.

I took a closer look at the images because I thought it might be due to the image format. But this is not a possible reason. They are all PNG images with comparable structure and size (dimensions and file-size) .

The tweets were always sent via Twitter's website - just as the days before had worked successfully.

I'm relatively sure it's a Twitter challenge. However, an explanation for the effect would be helpful, because then you could probably avoid it.

Any hints or ideas are welcome.

**Comment by schulle4u** [comment] 2018-09-21 11:01
Thanks for the report. I'm not working with images that often, therefore I haven't had the time to fully test this feature. 

Is your `robots.txt` blocking the twitterbot from fetching your metadata? You can try to add it to your robots file: 

```
User-agent:Twitterbot
Disallow:
```

According to twitter developers community, another problem can be caused by temporary network timeouts while fetching the metadata. To enforce reloading the images, Twitter suggests to add a random dummy parameter to the end of the image URL, e.g. `https://url/to/image.png?12345`. If I understand right, this will reload the image the next time the card is displayed. 

But please check the robots file first. Even if only a few images are affected, some users reported that this solved their problem. If the problem persists, I will add some randomness to the image URL.

**Comment by BsNoSi** [comment] 2018-09-24 10:54
Because I did not change the robots.txt between "working" and "not working" is must be something different. 

Adding a random "?1234" to the images *afterwards* does not lead success. Obviously, Twitter fetches an image only once, updating the link (without random form the beginning?) doesn't change anything.

Sending another tweet with same picture with appended random number, doesn't help – image is still not displayed. I will try with another one – as soon as available.

**Comment by schulle4u** [comment] 2019-01-04 11:36
Due to structural changes for my plugins I'm closing this issue and archive the repository. If this problem still exists, please reopen this issue in my [new plugins repository](https://github.com/schulle4u/yellow-plugins-schulle4u)

**Closed by schulle4u** 2019-01-04 11:36 UTC
Labels: help wanted
